language: ruby
notifications:
  email:
    recipients:
      - rafael.rabetti@gmail.com
rvm:
  - "2.3.1"
addons:
  postgresql: "9.6"
before_script:
  - echo "local all postgres trust" | sudo tee /etc/postgresql/9.6/main/pg_hba.conf
  - echo "local all all trust" | sudo tee /etc/postgresql/9.6/main/pg_hba.conf
  - sudo service postgresql reload
  - cd pesquini/
  - gem install bundler
  - gem install rspec rspec-rails simplecov
  - bundle install
  - psql -c "DROP DATABASE pesquini_development" || true
  - psql -c "DROP DATABASE pesquini_test" || true
  - psql -c "DROP USER pesquini" || true
  - psql -c "CREATE USER pesquini CREATEDB CREATEROLE INHERIT LOGIN" || true
  - psql -c "CREATE DATABASE pesquini_development WITH OWNER = pesquini" || true
  - psql -c "CREATE DATABASE pesquini_test WITH OWNER = pesquini" || true
  - cd script/
  - psql -d pesquini_development -f pesquini_development.sql
  - psql -d pesquini_test -f pesquini_development.sql
  - cd ..
  - bundle install
  # - cd pesquini
deploy:
  provider: heroku
  api_key:
    secure: e0ee41a1-482c-48d8-95c9-3bf1b8b6ddf5
  app: gcs-pesquini
  on:
    repo: GCSTrabalhoFinal/pesquini
script:
    - bundle exec rake db:setup
    - bundle exec rspec spec
    - bundle exec cucumber
